---
# Template configuration files for rhv

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ rhv_templates_copy }}"
  when: rhv_copy_templates
